spring:
  application:
    name: portfolio

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dummy}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true  # STARTTLS 필수 설정
          connectiontimeout: 10000 # 10초 타임아웃
          timeout: 10000
          writetimeout: 10000